name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Git config
        run: |
              git config --global user.email alice.silva@ccc.ufcg.edu.br
              git config --global user.name alicesilva
              git remote set-url origin https://alicesilva:${{ secrets.MY_PASSWORD }}@github.com/alicesilva/caju-test-frontend.git
      - name: Install dependencies
        run: yarn install

      - name: Deploy project
        run: yarn deploy